apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: example
spec:
  provider:
    gcpsm:
      projectID: yesod-istio
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: us-central1-c
          # name of the GKE cluster
          clusterName: cluster-1
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: yesod-istio
          # reference the sa from above
          serviceAccountRef:
            name: external-secret-wi
            namespace: external-secrets
